"""Test constants for eliminating magic values in test files."""

# Test threshold values
TEST_HIGH_SPAM_SCORE = 5.0
TEST_LOW_SPAM_SCORE = 3.0
TEST_MEDIUM_SPAM_SCORE = 7.0

# Test quality thresholds
TEST_EXCELLENT_QUALITY = 0.95
TEST_HIGH_QUALITY = 0.8
TEST_MEDIUM_QUALITY = 0.7
TEST_LOW_QUALITY = 0.5

# Test data counts
TEST_LARGE_DATASET = 1000
TEST_MEDIUM_DATASET = 100
TEST_SMALL_DATASET = 10
TEST_MINIMAL_DATASET = 5

# Test percentage values
TEST_SUCCESS_RATE = 96.0
TEST_HIGH_SUCCESS_RATE = 95.0
TEST_MEDIUM_SUCCESS_RATE = 80.0

# Test time values (hours)
TEST_MAX_HOURS = 72
TEST_LARGE_HOURS = 50
TEST_MEDIUM_HOURS = 24
TEST_SMALL_HOURS = 2

# Test processing values
TEST_RECORDS_PROCESSED = 1250
TEST_RECORDS_SUCCESSFUL = 1200
TEST_RECORDS_FAILED = 50
TEST_BATCH_SIZE = 500
TEST_SMALL_BATCH = 200
