"""Analytics and machine learning constants."""

# Model training constants
MIN_TRAINING_SAMPLES = 10
MIN_MODEL_ACCURACY = 0.8
BATCH_PROCESSING_SIZE = 1000

# Confidence thresholds for ML operations
HIGH_CONFIDENCE_THRESHOLD = 0.95
MEDIUM_CONFIDENCE_THRESHOLD = 0.8
LOW_CONFIDENCE_THRESHOLD = 0.7

# Analytics processing
DEFAULT_ANALYSIS_WINDOW = 30
MAX_ANALYSIS_WINDOW = 100
MIN_ANALYSIS_WINDOW = 5

# Forecasting constants
FORECAST_HORIZON_DAYS = 30
MIN_HISTORICAL_POINTS = 20
SEASONAL_PERIOD_DAYS = 7

# ML clustering constants
KMEANS_CLUSTERS = 5
KMEANS_INIT_COUNT = 10
DBSCAN_EPS = 0.5
DBSCAN_MIN_SAMPLES = 5

# Model defaults
DEFAULT_MODEL_ACCURACY = 0.7
DEFAULT_PEAK_HOUR = 12

# Forecasting validation bounds
MIN_CONFIDENCE_ADJUSTMENT = 0.1
MAX_CONFIDENCE_ADJUSTMENT = 2.0
MIN_UTILIZATION_PERCENTAGE = 0.0
MAX_UTILIZATION_PERCENTAGE = 100.0
MIN_TREND_CONFIDENCE = 0.0
MAX_TREND_CONFIDENCE = 1.0
MIN_DATA_QUALITY_SCORE = 0.0
MAX_DATA_QUALITY_SCORE = 1.0

# Time series analysis constants
TIME_SERIES_VALIDATION_WINDOW = 30
DATA_RETENTION_DAYS = 90
MIN_FORECAST_DAYS = 1
MAX_FORECAST_DAYS = 365
MIN_TREND_ANALYSIS_POINTS = 5
TREND_THRESHOLD_PERCENTAGE = 0.01
