"""Performance and timing constants."""

# Data requirements
MIN_DATA_POINTS = 10

# Timeout values (milliseconds)
DEFAULT_TIMEOUT_MS = 1000
EXTENDED_TIMEOUT_MS = 10000
SHORT_TIMEOUT_MS = 500

# Batch processing sizes
BATCH_SIZE_SMALL = 20
BATCH_SIZE_MEDIUM = 50
BATCH_SIZE_LARGE = 100
BATCH_SIZE_XLARGE = 1000

# Retry configuration
MAX_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_ATTEMPTS = 2
SINGLE_RETRY = 1

# Performance thresholds
MAX_PROCESSING_TIME_MS = 5000
WARNING_PROCESSING_TIME_MS = 2000

# HTTP timeout limits (seconds)
MIN_TIMEOUT_SECONDS = 1
MAX_TIMEOUT_SECONDS = 300

# Response size limits
RESPONSE_SIZE_BYTES_1KB = 1024
RESPONSE_SIZE_BYTES_1MB = 1024 * 1024
MAX_RESPONSE_SIZE_MB = 10

# HTTP status code ranges
MIN_HTTP_STATUS_CODE = 100
MAX_HTTP_STATUS_CODE = 599
HTTP_SUCCESS_MIN = 200
HTTP_SUCCESS_MAX = 300
HTTP_REDIRECT_MIN = 300
HTTP_REDIRECT_MAX = 400
HTTP_CLIENT_ERROR_MIN = 400
HTTP_SERVER_ERROR_MIN = 500

# HTTP security constants
HTTP_PORT_MIN = 1
HTTP_PORT_MAX = 65535
HTTP_HEADER_LENGTH_MAX = 100
HTTP_HEADER_VALUE_MAX = 8192
HTTP_RATE_LIMIT_PER_MINUTE = 60
ASCII_PRINTABLE_MIN = 32  # Space character - minimum printable ASCII
