"""Threshold and limit constants."""

# Confidence levels
CONFIDENCE_THRESHOLD_HIGH = 0.95
CONFIDENCE_THRESHOLD_MEDIUM = 0.8
CONFIDENCE_THRESHOLD_LOW = 0.7
SUCCESS_RATE_THRESHOLD = 0.90
MINIMUM_ACCURACY = 0.8

# Percentage and scaling
PERCENTAGE_SCALE = 100
HALF_PERCENTAGE = 50

# Voice and accessibility limits
VOICE_RATE_MIN = 0
VOICE_RATE_MAX = 100
VOICE_PITCH_MIN = 0
VOICE_PITCH_MAX = 100

# Sensitivity ranges
SENSITIVITY_MIN = 0
SENSITIVITY_MAX = 100
DEFAULT_SENSITIVITY = 50

# Accessibility scan speed limits
ACCESSIBILITY_SCAN_SPEED_MIN = 0.1
ACCESSIBILITY_SCAN_SPEED_MAX = 10.0

# Issue count thresholds for accessibility reports
ACCESSIBILITY_ISSUE_COUNT_HIGH = 5
ACCESSIBILITY_ISSUE_COUNT_MEDIUM = 10
ACCESSIBILITY_DISPLAY_LIMIT = 10
ACCESSIBILITY_CONTENT_PREVIEW_LENGTH = 500

# Goal management thresholds
GOAL_DECOMPOSITION_CRITERIA_LIMIT = 3
GOAL_RETRY_LIMIT = 3
AGENT_LEARNING_SAMPLE_MIN = 3
DETECTION_OCCURRENCE_MIN = 3

# Agent learning system constants
AGENT_PATTERN_RECENCY_DAYS = 30
AGENT_MODEL_UPDATE_EXPERIENCES = 100
AGENT_EXPERIENCE_HISTORY_LIMIT = 10000
AGENT_EXPERIENCE_KEEP_RECENT = 5000
AGENT_STRING_HASH_THRESHOLD = 20
AGENT_MODEL_MIN_EXPERIENCES = 10
AGENT_ACCURACY_TREND_MIN = 2
AGENT_RETRAINING_DAYS = 7

# Common iteration and count constants
DEFAULT_RETRY_COUNT = 3
MINIMUM_SAMPLES_COUNT = 2
SMALL_BATCH_SIZE = 10
MEDIUM_COUNT_THRESHOLD = 5
MAX_PERCENTAGE = 100.0

# String length and parameter limits
PARAMETER_LENGTH_LIMIT = 10000
MAX_RESULTS_DEFAULT = 1000
IDENTIFIER_LENGTH_LIMIT = 100
PERCENTAGE_CONFIDENCE_HIGH = 0.8
PERCENTAGE_CONFIDENCE_VERY_HIGH = 0.90
PERCENTAGE_CONFIDENCE_EXCELLENT = 0.95

# Quality thresholds
EXCELLENT_QUALITY = 0.95
GOOD_QUALITY = 0.8
ACCEPTABLE_QUALITY = 0.7
POOR_QUALITY = 0.5

# Risk and safety thresholds
SAFETY_RISK_LIMIT = 0.7
HIGH_RISK_THRESHOLD = 0.8
MEDIUM_RISK_THRESHOLD = 0.5
LOW_RISK_THRESHOLD = 0.3
EMERGENCY_RISK_THRESHOLD = 0.95
CRITICAL_RISK_THRESHOLD = 0.85
WARNING_RISK_THRESHOLD = 0.7
MINIMAL_RISK_THRESHOLD = 0.1

# Pattern detection and similarity thresholds
PATTERN_SIMILARITY_THRESHOLD = 0.8
PATTERN_EFFECTIVENESS_THRESHOLD = 0.6
PATTERN_ADAPTATION_THRESHOLD = 0.8
HIGH_SIMILARITY_THRESHOLD = 0.8
MEDIUM_SIMILARITY_THRESHOLD = 0.5

# Detection limits and counts
MINIMUM_PATTERN_OCCURRENCES = 3
SPAM_DETECTION_THRESHOLD = 3
MAX_EXAMPLES_LIMIT = 3
DIMENSION_CHANGE_PATTERN_MIN = 3
CONTEXT_HISTORY_LIMIT = 50
TEXT_LENGTH_LIMIT = 50

# Phone number format lengths
PHONE_NUMBER_WITH_COUNTRY_CODE = 12  # +1 plus 10 digits
PHONE_NUMBER_STANDARD_LENGTH = 10  # Standard US phone number

# Significance and change thresholds
SIGNIFICANCE_THRESHOLD_HIGH = 0.8
SIGNIFICANCE_THRESHOLD_MEDIUM = 0.5
SIGNIFICANCE_THRESHOLD_LOW = 0.3
CHANGE_NOTIFICATION_THRESHOLD = 0.3

# Performance and quality level thresholds
EXCELLENT_PERFORMANCE_THRESHOLD = 0.95
VERY_HIGH_PERFORMANCE_THRESHOLD = 0.9
HIGH_PERFORMANCE_THRESHOLD = 0.8
MINIMUM_PERFORMANCE_THRESHOLD = 0.7
POOR_PERFORMANCE_THRESHOLD = 0.5

# Success rate and accuracy thresholds
MINIMUM_SUCCESS_RATE = 0.7
HIGH_SUCCESS_RATE = 0.9
MINIMUM_ACCURACY_THRESHOLD = 0.7
HIGH_ACCURACY_THRESHOLD = 0.9
CONTEXT_SIMILARITY_THRESHOLD = 0.7

# Confidence level boundaries
VERY_HIGH_CONFIDENCE_BOUNDARY = 0.95
HIGH_CONFIDENCE_BOUNDARY = 0.75
MEDIUM_CONFIDENCE_BOUNDARY = 0.5

# Evolution and maturity thresholds
MATURITY_THRESHOLD = 0.95
RESOURCE_WARNING_THRESHOLD = 0.9

# Accessibility and compliance thresholds
ACCESSIBILITY_EXCELLENT_SCORE = 100.0
ACCESSIBILITY_GOOD_SCORE = 80.0
ACCESSIBILITY_ACCEPTABLE_SCORE = 70.0
ACCESSIBILITY_POOR_SCORE = 50.0
ACCESSIBILITY_MIN_VOLUME = 0.1
ACCESSIBILITY_MAX_VOLUME = 10.0
ACCESSIBILITY_CONFIDENCE_THRESHOLD = 0.8
ACCESSIBILITY_BATTERY_HIGH = 85
ACCESSIBILITY_BATTERY_MEDIUM = 80
ACCESSIBILITY_BATTERY_LOW = 75
ACCESSIBILITY_BATTERY_CRITICAL = 70
ACCESSIBILITY_BATTERY_ALERT = 10
